### PR TITLE
Adds saving functionality to currency and quantity selections.

### LINKED ISSUE #27: Feature request: Save currency and quantity selections.
It would be helpful to be able to select a currency, enter an amount and have both saved for the next time a user visits.

### PR DESCRIPTION
**Pull request by jimthedev**
Fixes #27 by adding autosave to currency and quantity selections.

### CODE REVIEW

**Comment by chrisdwheatley** [comment]
Thanks for the pull request! I really like this feature, it's not something I'd even thought of adding.

I'd like to simplify it a bit if you don't mind though. Can we make it so it just stores the previously entered DOGE amount and the previously selected FIAT currency only? I think the simpler the better for now. I checked out your code and had a quick play so I'm happy to make the amendments if you'd like.

**Comment by jimthedev** [comment]
No problem! Thanks for making the app open source. I am a user of the site so when I found myself always typing my last amount in, I figured I'd contribute. 

Yes, that's totally possible. I will make the changes tonight and will roll them into the existing PR. I'll reply here after they are done.

Cheers!

**Comment by jimthedev** [comment]
Hey there,

Ok, that should do it. I pushed up my changes which have been rolled into the previously opened PR. 

Jim

**Comment by chrisdwheatley** [comment]
Perfect, thanks! I've just deployed the new code so you can see your changes working on the live site right now =)

**Pull request merged**
