### PR TITLE
No More jQuery In Widget

### PR DESCRIPTION
**Pull request by 7THStage**
I've never submitted a pull request before, so if I mess this up, I'm sorry. Otherwise, hopefully this is what you were thinking in issue #20. A bit more testing probably wouldn't hurt, and I wasn't sure what browsers you're aiming to support. But anyway, here's some code.

Tested in the latest versions of Firefox, Chrome, Opera, and Safari on Mac 10.9.1. Tested in IE10 on Windows 7.

### CODE REVIEW

**Comment by chrisdwheatley** [comment]
Woah, I really wasn't expecting anyone to pick this up. Thank you! I've been avoiding it like the plague.

Will take a look over the code and do some further testing.

**Comment by 7THStage** [comment]
Glad I could take it off your hands then. :) I write way too much JS, but I actually enjoy it, so that makes it okay. Besides, it pains me to see jQuery included for only a couple of functions. It's a beast. Anyway, if you find any problems, let me know which browser and OS combo and I should be able to fix it.

**Comment by chrisdwheatley** [comment]
Will deploy this shortly, going to make some enhancements to the widget page to go alongside the enhancement. Thanks again!

**Comment by chrisdwheatley** [comment]
Sorry for the delay, your code is now live:
- http://wowsuch.io/widgets
- http://wowsuch.io/widget/wow-such-widget.js

Thanks for your contribution =)

**Pull request merged**
